language: cpp
compiler:
    - clang
    - gcc
os: linux

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
            - kalakris-cmake
        packages:
            - cmake
            - clang-3.7
            - clang-3.7
            - g++-5
            - gcc-5

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make