language: cpp
compiler:
    - clang
    - gcc
os: linux

addons:
apt:
    sources:
        - llvm-toolchain-precise-3.7
        - ubuntu-toolchain-r-test
    packages:
        - clang-3.7
        - clang-3.7
        - g++-5
        - gcc-5

install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER=${COMPILER}

script: make